### ISSUE TITLE
consume api on webbrowser

### ISSUE THREAD

**Issue by ebisbe** [flickr/flickr-sdk#108]
Hello,
Is there a way to consume the api at web browser level with the auhtentication with this SDK?

**Comment by youngvo** [comment]
The same question here. Anyone has a solution to export the SDK to a javascript single file for distribution.

Thanks,

**Comment by jeremyruppel** [comment]
@ebisbe Since OAuth 1.0 requires you to provide your application's key and secret for signing requests, we intentionally don't support API methods that require authentication in the browser. You can still call any API methods that don't require authentication ([permissions = `none` in this table](https://github.com/flickr/flickr-sdk#flickr)) by just [using your API key](https://github.com/flickr/flickr-sdk#new-flickrauth).

@youngvo Totally! Bundling this module has been tested with [browserify](http://browserify.org/) and should also work with other asset packagers like [webpack](https://webpack.github.io/) and [rollup](https://rollupjs.org/). We definitely recommend using an asset packager for producing and optimizing client-side bundles.

**Comment by jeremyruppel** [comment]
@youngvo starting with v3.2.0 you can find a ready-to-go browserified version of this module at `node_modules/flickr-sdk/flickr-sdk.js` in the installed node module. You'll still need to install this module via npm and the browserified bundle isn't minified or anything, but hopefully it should let you get started quickly!

**Comment by ebisbe** [comment]
@jeremyruppel I've commented on https://github.com/flickr/flickr-sdk/pull/64/files#diff-ccc0734f65dd7a299409ff07d35be095
