### ISSUE TITLE
OAuth 1.0 is not supported in the browser

### ISSUE THREAD

**Issue by zerolfc** [flickr/flickr-sdk#114]
Do you know why im getting this error? please help!
I am using WebPack.

Here is the code:

```
const Flickr = require('flickr-sdk/flickr-sdk.js');
const {ipcRenderer, remote} = require('electron');
const oauth = new Flickr.OAuth(
    remote.process.env.FLICKR_CONSUMER_KEY,
    remote.process.env.FLICKR_CONSUMER_SECRET
);
```
![screenshot from 2017-10-01 20-50-34](https://user-images.githubusercontent.com/5167436/31058348-34d527e0-a6ea-11e7-886f-ba5e1da98598.png)

**Comment by pdokas** [comment]
Hey there, the Flickr SDK doesn’t support OAuth 1.0 in the browser [as mentioned here](https://github.com/flickr/flickr-sdk#browser-usage) because of the security model. OAuth 1.0 requires your app’s secret and that should be kept private at all times so if you were to make it available in the browser then your secret would be compromised.
