### ISSUE TITLE
Caching queries

### ISSUE THREAD

**Issue by ebisbe** [flickr/flickr-sdk#117]
Would you recomend caching queries? I asume that is not posible with this sdk.

**Comment by jeremyruppel** [comment]
Caching API calls might make sense for your application depending on what you're doing, but it's definitely out of scope in terms of core functionality in this SDK. However, since this SDK is really just a thin layer over superagent, you can use any superagent plugin you'd like by just calling `.use()` on a Request instance. I haven't used this personally, but there's a [superagent-cache plugin](https://github.com/jpodwys/superagent-cache-plugin) out there that looks pretty nice and might do the trick!
