### ISSUE TITLE
Why there are private actions only available for Flickr?

### ISSUE THREAD

**Issue by ebisbe** [flickr/flickr-sdk#165]
Hello, 

I need the total amount of groups a photo belongs to. Right now through the api I have to call `photos.getAllContexts` and do a count on the pool array. That's overkill when you already have a get totals with the amount that is being used on the website but not on specified on the api. 

```
photos.getAllContexts {
  photo_id: '***',
  per_type_limit: 6,
  get_totals: 1,
  get_all_galleries: 1,
  no_faves_context: 1,
  primary_photo_extras: 'url_sq, url_t, url_s, url_m, needs_interstitial',
  extras: 'can_addmeta,can_comment,can_download,can_print,can_share,contact,content_type,count_comments,count_faves,count_views,date_taken,date_upload,description,icon_urls_deep,isfavorite,ispro,license,media,needs_interstitial,owner_name,owner_datecreate,path_alias,perm_print,realname,rotation,safety_level,secret_k,secret_h,url_sq,url_q,url_t,url_s,url_n,url_w,url_m,url_z,url_c,url_l,url_h,url_k,url_3k,url_4k,url_f,url_5k,url_6k,url_o,visibility,visibility_source,o_dims,publiceditability,system_moderation,datecreate,date_activity,eighteenplus,invitation_only,needs_interstitial,non_members_privacy,pool_pending_count,privacy,member_pending_count,icon_urls,date_activity_detail,muted,owner_name,path_alias,realname,sizes,url_sq,url_q,url_t,url_s,url_n,url_w,url_m,url_z,url_c,url_l,url_h,url_k,url_3k,url_4k,url_5k,url_6k,needs_interstitial'
}
```

I don't need the extras ( may come in handy in the future ) but I would like to be able to use the `get_totals` and `per_type_limit` so I can get a fast response. What do you think @jeremyruppel @alex-seville ??

**Comment by jeremyruppel** [comment]
I'm sorry you're having issues with the way the public API response is set up. Like many websites, Flickr has features and functionality intended for Flickr use only. If you'd like to request a change to a public API response, we don't do that lightly or often since our API doesn't have versioning, but please feel free to ask in the [API group](https://www.flickr.com/groups/api/) (which is the appropriate place for a request such as this, as we can't actually do anything about this in the SDK).

I'd also like to remind anyone reading this that undocumented APIs and params are undocumented _for a reason_ and may change without notice at any time (and often do, as they are not public). Best to stick with [public API methods](https://www.flickr.com/services/api/).
