### ISSUE TITLE
Can't pass integer extra params

### ISSUE THREAD

**Issue by jeremen** [flickr/flickr-sdk#5]
For example: 
```
flickr.request().media().search(term).get({
      per_page: 10
}).then(response => {
      console.log(response);
});
```

Will result in: _Param per_page with type integer not of the expected type: number_

**Comment by TomCaserta** [comment]
Yep, this is because the schema specifies both "number" and "integer" as types whereas the validator will convert all javascript numbers to "integer" as its type. Perhaps just relax the validator a bit and not differentiate between number and integer (presuming number means any number - not just whole numbers) or alternatively actually check if a number .isInteger()
